export const ACTION_TYPE = {
	LOADING_START: 'LOADING_START',
	LOADING_END: 'LOADING_END',
	SET_TODOS: 'SET_TODOS',
	ADD_TODO: 'ADD_TODO',
	REMOVE_TODO: 'REMOVE_TODO',
	UPDATE_TODO: 'UPDATE_TODO',
	SET_SEARCH: 'SET_SEARCH',
	RESET_SEARCH: 'RESET_SEARCH',
	SET_PAGE: 'SET_PAGE',
	SET_ALPHA_SORT: 'SET_ALPHA_SORT',
};
